#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'anagram' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def anagram(s):
    # Write your code here
    

    c=0
    if(len(s)%2!=0):
       return("-1")
    else:
       s1=list(s[0:len(s)//2])
       s2=list(s[len(s)//2:])
       
       for i in s1:
          if(i not in s2):
             c=c+1
          else:
            s2.remove(i)
       return(c)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = anagram(s)

        fptr.write(str(result) + '\n')

    fptr.close()
