#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'closestNumbers' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def closestNumbers(arr):
    # Write your code here
    arr.sort()
    diff = abs(arr[0]-arr[1])
    L= []
    for i in range(len(arr)-1):
        d = abs(arr[i]-arr[i+1])
        if d==diff:
            L+= [arr[i], arr[i+1]]
            diff =d
        elif d<diff:
            L= [arr[i], arr[i+1]]
            diff=d
    return L


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
