#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def pangrams(s):
    # Write your code here
    c=0

    a='abcdefghijklmnopqrstuvwxyz '
    m=s.lower()
    for i in a :
       if(i not in m):
          c=2
          break
          
                
    if(c==2):
      return("not pangram")   
    else:
      return("pangram")
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
