#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    cp=0
    cn=0
    c0=0
    for i in range(len(arr)):
        if(arr[i]>0):
            cp=cp+1
        elif(arr[i]==0):
            c0=c0+1
        elif(arr[i]<0):
            cn=cn+1
    print(cp/n)
    print(cn/n)
    print(c0/n)
    
    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
